# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [2]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt
pip install numpy --upgrade

SyntaxError: invalid syntax (1550180525.py, line 2)

### 2. Install/Upgrade another package (e.g. Pandas) 

In [3]:
pip install pandas --upgrade

Note: you may need to restart the kernel to use updated packages.


### 3. Import NumPy as <i> np </i>

In [1]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [3]:
array_hw_1 = np.array([4,5,7,10])

### 5. Display the new array on screen

In [7]:
print(array_hw_1)

[ 4  5  7 10]


### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [8]:
array_hw_2 = array_hw_1.reshape(2,2)

In [9]:
print(array_hw_2)

[[ 4  5]
 [ 7 10]]


### 7. Call the <i> np.mean() </i> function on each array

In [12]:
print(np.mean(array_hw_1))


6.5
6.5


In [13]:
print(np.mean(array_hw_2))

6.5


### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [14]:
np.mean(array_hw_2, axis=1)

array([4.5, 8.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [15]:
np.mean(array_hw_1, axis=0)

np.float64(6.5)

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [22]:
array_int = np.array(array_hw_2,dtype=np.int64)
print(np.mean(array_int))
print(np.mean(array_hw_2))

6.5
6.5
