## Importing the Packages

In [403]:
import numpy as np

In [404]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

## Importing the Data

In [405]:
raw_data = np.genfromtxt("loan-data.csv", delimiter=';', skip_header=1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [406]:
np.isnan(raw_data).sum()

np.int64(88005)

In [407]:
temporary_fill = np.nanmax(raw_data)+1
temporary_mean = np.nanmean(raw_data, axis=0)

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\2088029289.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis=0)


In [408]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [409]:
temporary_stats = np.array([np.nanmin(raw_data,axis=0), temporary_mean,np.nanmax(raw_data,axis=0)])

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\2481335527.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data,axis=0), temporary_mean,np.nanmax(raw_data,axis=0)])


In [410]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [411]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [412]:
column_num = np.argwhere(np.isnan(temporary_mean)== False).squeeze()
column_num

array([ 0,  2,  4,  6,  7, 13])

### Re-importing the Dataset

In [413]:
loan_data_str = np.genfromtxt("loan-data.csv", delimiter=';', skip_header=1,autostrip=True,usecols=column_strings,dtype=np.str_)
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [414]:
loan_data_num = np.genfromtxt("loan-data.csv ", delimiter=';', skip_header=1,autostrip=True,usecols=column_num, filling_values=temporary_fill)
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [415]:
header_full = np.genfromtxt("loan-data.csv", delimiter=';', skip_footer=raw_data.shape[0],autostrip=True,dtype=np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [416]:
header_str, header_num = header_full[column_strings], header_full[column_num]

In [417]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [418]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [419]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [420]:
checkpoint_test = checkpoint("checkpoint-test", header_str, loan_data_str)

In [421]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [422]:
np.array_equal(checkpoint_test['data'], loan_data_str)

True

## Manipulating String Columns

In [423]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [424]:
header_str[0]= "issue_date"

In [425]:
loan_data_str


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [426]:
np.unique(loan_data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [427]:
loan_data_str[:,0] = np.chararray.strip(loan_data_str[:,0], "-15")

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\1184924524.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_str[:,0] = np.chararray.strip(loan_data_str[:,0], "-15")


In [428]:
np.unique(loan_data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [429]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [430]:
for i in range(13):
    loan_data_str[:,0] = np.where(loan_data_str[:,0] == months[i], str(i), loan_data_str[:,0])

### Loan Status

In [431]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [432]:
np.unique(loan_data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [433]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [434]:
loan_data_str[:,1] = np.where(np.isin(loan_data_str[:,1], status_bad),0,1)

In [435]:
np.unique(loan_data_str[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [436]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [437]:
np.unique(loan_data_str[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [438]:
loan_data_str[:,2] = np.chararray.strip(loan_data_str[:,2], "months")

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\832295033.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_str[:,2] = np.chararray.strip(loan_data_str[:,2], "months")


In [439]:
header_str[2] = "term_months"

In [440]:
loan_data_str[:,2] = np.where(loan_data_str[:,2] == '', '60', loan_data_str[:,2])
loan_data_str[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [441]:
np.unique(loan_data_str[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

### Grade and Subgrade

In [442]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [443]:
np.unique(loan_data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [444]:
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [445]:
for i in np.unique(loan_data_str[:,3])[1:]:
    loan_data_str[:,4] = np.where((loan_data_str[:,4] == '') & (loan_data_str[:,3] == i),
                                      i + '5',
                                      loan_data_str[:,4])

In [446]:
np.unique(loan_data_str[:,4], return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [447]:
loan_data_str[:,4] = np.where(loan_data_str[:,4] == '', 'H1', loan_data_str[:,4])

In [448]:
np.unique(loan_data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [449]:
loan_data_str = np.delete(loan_data_str, 3,axis=1)

In [450]:
loan_data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [451]:
header_str = np.delete(header_str,3)

In [452]:
header_str[3]

np.str_('sub_grade')

#### Converting Sub Grade

In [453]:
np.unique(loan_data_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [454]:
keys = list(np.unique(loan_data_str[:,3]))                         
values = list(range(1, np.unique(loan_data_str[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [455]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [456]:
for i in np.unique(loan_data_str[:,3]):
    loan_data_str[:,3] = np.where(loan_data_str[:,3] == i, str(dict_sub_grade[i]), loan_data_str[:,3])

### Verification Status

In [457]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [458]:
np.unique(loan_data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [459]:
loan_data_str[:,4] = np.where((loan_data_str[:,4] == '') | (loan_data_str[:,4] == 'Not Verified'), 0, 1)

In [460]:
np.unique(loan_data_str[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [461]:
loan_data_str[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [462]:
np.chararray.strip(loan_data_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\1539212140.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  np.chararray.strip(loan_data_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [463]:
loan_data_str[:,5] = np.chararray.strip(loan_data_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

C:\Users\PF6441\AppData\Local\Temp\ipykernel_39096\638535621.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_str[:,5] = np.chararray.strip(loan_data_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


In [464]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [465]:
loan_data_num[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [466]:
loan_data_str[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [467]:
np.array_equal(loan_data_num[:,0].astype(dtype = np.int32),loan_data_str[:,5].astype(dtype = np.int32))

True

In [468]:
loan_data_str = np.delete(loan_data_str, 5, axis=1)
header_str = np.delete(header_str,5)

In [469]:
loan_data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [470]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [471]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [472]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### State Address

In [473]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [474]:
header_str[5] = 'state_address'

In [475]:
states_names, states_count = np.unique(loan_data_str[:,5],return_counts=True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [476]:
loan_data_str[:,5] = np.where(loan_data_str[:,5] == '', '0', loan_data_str[:,5])


In [477]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [478]:
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_west), '1', loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_south), '2', loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_midwest), '3', loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_east), '4', loan_data_str[:,5])


In [479]:
np.unique(loan_data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [480]:
loan_data_str


array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [481]:
loan_data_str = loan_data_str.astype(np.int32)

### Checkpoint 1: Strings

In [482]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_str,loan_data_str)

In [483]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [484]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [485]:
np.array_equal(checkpoint_strings["data"], loan_data_str)

True

## Manipulating Numeric Columns

In [486]:
np.isnan(loan_data_num).sum()

np.int64(0)

In [487]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Substitute "Filler" Values

In [488]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [489]:
temporary_fill

np.float64(68616520.0)

In [490]:
np.isin(loan_data_num[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [491]:
np.isin(loan_data_num[:,0], temporary_fill).sum()

np.int64(0)

In [492]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [493]:
temporary_stats[:,column_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [494]:
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [495]:
loan_data_num[:,2] = np.where(loan_data_num[:,2] == temporary_fill, 
                                  temporary_stats[0, column_num[2]],
                                  loan_data_num[:,2])
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [496]:
temporary_stats[0,3]

np.float64(nan)

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [497]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [498]:
for i in [1,3,4,5]: 
    loan_data_num[:,2] = np.where(loan_data_num[:,2] == temporary_fill, 
                                  temporary_stats[2, column_num[2]],
                                  loan_data_num[:,2])
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [499]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [500]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter=',', autostrip=True, skip_footer=1, usecols=1)
EUR_USD

array([ nan, 1.21, 1.15, 1.12, 1.12, 1.15, 1.14, 1.12, 1.17, 1.15, 1.15, 1.11])

In [501]:
np.unique(loan_data_str[:,0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [502]:
exchange_rate = loan_data_str[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)  
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == 0,
                             np.mean(EUR_USD),
                             exchange_rate)      


In [503]:
exchange_rate.shape

(10000,)

In [504]:
loan_data_num.shape

(10000, 6)

In [505]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [506]:
header_num = np.concatenate((header_num, np.array(['exchange_rate'])))

In [507]:
loan_data_num = np.hstack((loan_data_num, exchange_rate))


In [508]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [509]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [510]:
columns_dollar = np.array([1,2,4,5])

In [511]:
loan_data_num[:,6]

array([1.12,  nan, 1.17, ..., 1.15, 1.12, 1.11])

In [512]:
for i in columns_dollar:
    loan_data_num = np.hstack((loan_data_num, np.reshape(loan_data_num[:,i] / loan_data_num[:,6], (10000,1))))

In [513]:
loan_data_num.shape

(10000, 11)

#### Expanding the header

In [514]:
header_additional = np.array([column_name + '_EUR' for column_name in header_num[columns_dollar]])

In [515]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [516]:
header_num = np.concatenate((header_num,header_additional))

In [517]:
header_num[columns_dollar] = np.array([column_name + '_EUR' for column_name in header_num[columns_dollar]])

In [518]:
header_num

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [519]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [520]:
header_num = header_num[columns_index_order]

In [521]:
loan_data_num = loan_data_num[:,columns_index_order]

### Interest Rate

In [522]:
loan_data_num[:,5]

array([      13.33, 68616520.  , 68616520.  , ..., 68616520.  ,       16.55, 68616520.  ])

In [523]:
loan_data_num[:,5] = loan_data_num[:,5]/100

In [524]:
loan_data_num[:,5]

array([     0.13, 686165.2 , 686165.2 , ..., 686165.2 ,      0.17, 686165.2 ])

### Checkpoint 2: Numeric

In [525]:
checkpoint_numeric = checkpoint("Chekpoint-Numeric", header_num,loan_data_num)

In [526]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_EUR', 'loan_amnt_EUR', 'funded_amnt_EUR', 'funded_amnt_EUR', 'int_rate',
        'installment_EUR', 'installment_EUR', 'total_pymnt_EUR', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31117.77, ...,     9452.96,     8404.43,        1.12],
        [57693261.  ,    30000.  ,         nan, ...,     4679.7 ,         nan,         nan],
        [59432726.  ,    15000.  ,    12813.94, ...,     1969.83,     1682.75,        1.17],
        ...,
        [50415990.  ,    10000.  ,     8731.3 , ...,     2185.64,     1908.35,        1.15],
        [46154151.  , 68616520.  , 61044553.16, ...,     3199.4 ,     2846.34,        1.12],
        [66055249.  ,    10000.  ,     9041.59, ...,      301.9 ,      272.97,        1.11]]))

## Creating the "Complete" Dataset

In [527]:
checkpoint_strings['data'].shape

(10000, 6)

In [528]:
checkpoint_numeric['data'].shape

(10000, 11)

In [529]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [530]:
loan_data

array([[48010226.  ,    35000.  ,    31117.77, ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,         nan, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    12813.94, ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8731.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  , 68616520.  , 61044553.16, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9041.59, ...,        4.  ,        0.  ,        3.  ]])

In [532]:
np.isnan(loan_data).sum()

np.int64(6350)

In [533]:
header_full= np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

## Sorting the New Dataset

In [534]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [535]:
loan_data

array([[  373332.  ,     9950.  ,     8682.37, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10471.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8265.4 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5063.29, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3616.64, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19529.83, ...,        3.  ,        0.  ,        2.  ]])

In [536]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Storing the New Dataset

In [539]:
loan_data = np.vstack((header_full, loan_data))

In [540]:
np.savetxt("loan-data-preprocessed.csv", loan_data,fmt="%s", delimiter=',')