# Preprocessing with NumPy

In [2]:
import numpy as np

## Checking for Missing Values

In [3]:
lendin_co = np.loadtxt("Lending-company-Numeric.csv", delimiter=',')

In [4]:
lendin_co_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter=';')

In [5]:
np.isnan(lendin_co_nan).sum()

np.int64(260)

In [6]:
lendin_co_nan_wdata = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter=';',filling_values=0)
np.isnan(lendin_co_nan_wdata).sum()

np.int64(0)

In [8]:
temporary_fill = np.nanmax(lendin_co_nan_wdata).round(2)+1
temporary_fill

np.float64(64002.0)

In [14]:
lendin_co_nan_wdata = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter=';',filling_values=temporary_fill)
np.isnan(lendin_co_nan_wdata).sum()

np.int64(0)

## Substituting Missing Values

In [15]:
temporary_mean = np.nanmean(lendin_co_nan, axis=0).round(2)
temporary_mean[0]

np.float64(2250.25)

In [16]:
temporary_fill

np.float64(64002.0)

In [17]:
np.mean(lendin_co_nan_wdata[:,0]).round(2)

np.float64(4263.25)

In [19]:
temporary_mean[0]

np.float64(2250.25)

In [18]:
lendin_co_nan_wdata[:,0]= np.where(lendin_co_nan_wdata[:,0]== temporary_fill, \
                                   temporary_mean[0], lendin_co_nan_wdata[:,0])
np.mean(lendin_co_nan_wdata[:,0]).round(2)

np.float64(2250.25)

In [20]:
for i in range(lendin_co_nan_wdata.shape[1]):
    lendin_co_nan_wdata[:,i]= np.where(lendin_co_nan_wdata[:,i]== temporary_fill, \
                                       temporary_mean[i], lendin_co_nan_wdata[:,i])


## Reshaping

In [20]:
lendin_co.shape


(1043, 6)

In [24]:
lendin_reshaped = np.reshape(lendin_co, (1,6, 1043))
lendin_reshaped

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
        [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

In [29]:
np.delete(lendin_co,(0,2,4),axis=1)


array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

In [27]:
lendin_co.size

6258

## Removing Values

## Sorting Data

In [41]:
np.sort(lendin_co).shape

(1043, 6)

In [37]:
np.sort(lendin_co, axis=None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [33]:
np.set_printoptions(suppress=True)

In [40]:
-np.sort(lendin_co)

array([[   -40.,   -365.,  -2000.,  -3121.,  -4241., -13621.],
       [   -40.,   -365.,  -2000.,  -3061.,  -4171., -15041.],
       [   -40.,   -365.,  -1000.,  -2160.,  -3280., -15340.],
       ...,
       [   -40.,   -365.,  -2000.,  -4201.,  -5001., -16600.],
       [   -40.,   -365.,  -1000.,  -2080.,  -3320., -15600.],
       [   -40.,   -365.,  -2000.,  -4601.,  -4601., -16600.]])

In [44]:
np.sort(lendin_co)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [45]:
np.sort(lendin_co[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

## Argument Functions

### np.argsort()

In [46]:
np.argsort(lendin_co)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]])

### np.argwhere()

In [48]:
np.argwhere(lendin_co == False)

array([[116,   4],
       [430,   3]])

In [49]:
lendin_co[116]

array([ 1000.,    50.,   365., -1450.,     0., 13850.])

In [50]:
np.argwhere(lendin_co %2 ==0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]])

In [51]:
np.isnan(lendin_co_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [52]:
np.argwhere(np.isnan(lendin_co_nan))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [21]:
lendin_co_nan[175]


array([ 2000.,    nan,    nan,  1851.,  3051., 13561.])

In [22]:
for arr in np.argwhere(np.isnan(lendin_co_nan)):
    lendin_co_nan[arr[0],arr[1]] = 0

## Shuffling Data

In [316]:
np.random.shuffle(lendin_co)
lendin_co

array([[ 1000.,    40.,   365.,  2100.,  3600., 10000.],
       [ 2000.,    40.,   365.,  3419.,  4619., 14469.],
       [ 2000.,    50.,   365.,  1551.,  2701.,  6351.],
       ...,
       [ 1000.,    50.,   365., -1860.,  -440., 12200.],
       [ 2000.,    40.,   365.,  3561.,  4701., 15851.],
       [ 2000.,    40.,   365.,  3128.,  4281., 15781.]])

In [317]:
from numpy.random import shuffle

In [334]:
shuffle(lendin_co)
lendin_co

array([[ 2000.,    40.,   365.,  3440.,  4580., 12460.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.],
       [ 4000.,    50.,   365.,  5550.,  6900., 15950.],
       ...,
       [ 2500.,    50.,   365.,  2050.,  3850., 18200.],
       [ 4000.,    50.,   365.,  5750.,  7350., 22250.],
       [ 1000.,    40.,   365.,  3500.,  5000., 15600.]])

In [55]:
from numpy.random import PCG64 as pcg
from numpy.random import Generator as gen

In [337]:
gen_arr = gen(pcg(seed = 34))
gen_arr.shuffle(lendin_co)
lendin_co

array([[ 2000.,    40.,   365.,  3101.,  4161., 10951.],
       [ 2000.,    40.,   365.,  3201.,  4401., 14001.],
       [ 2000.,    40.,   365.,  3200.,  4320., 16600.],
       ...,
       [ 4000.,    50.,   365.,  5400.,  6900., 22250.],
       [ 2000.,    40.,   365.,  7901.,  7901., 16600.],
       [ 9000.,   165.,   365., 14460., 18050., 37903.]])

## Casting

In [11]:
lendin_co_new = np.genfromtxt('Lending-Company-Total-Price.csv', delimiter=',', dtype = np.str_, skip_header= 1, usecols = [1,2,4])
lendin_co_new

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [13]:
lendin_co_new[:,0] = np.chararray.strip(lendin_co_new[:,0], "id_")
lendin_co_new[:,1] = np.chararray.strip(lendin_co_new[:,1], "Product ")
lendin_co_new[:,2] = np.chararray.strip(lendin_co_new[:,2], "Location ")
lendin_co_new

C:\Users\PF6441\AppData\Local\Temp\ipykernel_4516\3786938188.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lendin_co_new[:,0] = np.chararray.strip(lendin_co_new[:,0], "id_")
C:\Users\PF6441\AppData\Local\Temp\ipykernel_4516\3786938188.py:2: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lendin_co_new[:,1] = np.chararray.strip(lendin_co_new[:,1], "Product ")
C:\Users\PF6441\AppData\Local\Temp\ipykernel_4516\3786938188.py:3: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lendin_co_new[:,2] = np.chararray.strip(lendin_co_new[:,2], "Location ")


array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

## Stripping Data

## Stacking

In [23]:
np.stack((lendin_co[:,0],lendin_co[:,1]))

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]])

In [24]:
np.transpose(lendin_co[:,:2])

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]])

In [26]:
np.stack((lendin_co[:,0],lendin_co[:,1], lendin_co[:,2]), axis=1)

array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]])

In [27]:
lendin_co_nan.shape

(1043, 6)

In [37]:
np.dstack((lendin_co,lendin_co_nan))[0]

array([[ 2000.,  2000.],
       [   40.,    40.],
       [  365.,   365.],
       [ 3121.,  3121.],
       [ 4241.,  4241.],
       [13621., 13621.]])

In [38]:
np.vstack((lendin_co_nan,lendin_co))[0]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

In [40]:
np.hstack((lendin_co,lendin_co_nan))[0]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3121.,  4241., 13621.])

In [43]:
np.dstack((lendin_co,lendin_co_nan))[0,:,0]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

In [48]:
np.stack((lendin_co,lendin_co_nan), axis = -1)[0]

array([[ 2000.,  2000.],
       [   40.,    40.],
       [  365.,   365.],
       [ 3121.,  3121.],
       [ 4241.,  4241.],
       [13621., 13621.]])

## Concatenate

In [51]:
np.concatenate((lendin_co[1], lendin_co[2]))

array([ 2000.,    40.,   365.,  3061.,  4171., 15041.,  1000.,    40.,
         365.,  2160.,  3280., 15340.])

In [57]:
np.concatenate((lendin_co,lendin_co_nan), axis = 1).shape

(1043, 12)

## Unique 

In [61]:
np.unique(lendin_co[:,1], return_counts=True, return_index=True)

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))